[package]
name = "actix-web-test"
version = "0.1.0"
authors = ["Ruan L. Nunes <ruanrln@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

actix-web = "^2"
actix-files = "*"
actix-rt = "^1"
